_BASE_: '../temporal_single_timeframe.yml'

TAG: 'temporal_pon_setting'

PRETRAINED:
  PATH: '/home/wayve/experiments/nuscenes/single_timeframe/10August2021at11:03:17UTC_vm-prod-training-dgx-05_pyramid_occupancy_network_setting/default/version_0/checkpoints/epoch=9-step=16260.ckpt'

DATASET:
  FILTER_INVISIBLE_VEHICLES: False

LIFT:
  X_BOUND: [-50.0, 50.0, 0.25]
  Y_BOUND: [-25.0, 25.0, 0.25]
