MODEL:
  MM:
    BBOX_BACKBONE: 
      type: SECOND
      in_channels: 128
      layer_nums: [3, 5, 5]
      layer_strides: [2, 2, 2]
      norm_cfg: 
        type: naiveSyncBN2d
        eps: 0.001
        momentum: 0.01
      # out_channels: [128, 256, 512]
      out_channels: [128, 256, 512]
