MODEL:
  MM:
    BBOX_BACKBONE: 
      type: SECOND
      in_channels: 64
      layer_nums: [3, 5, 5]
      layer_strides: [2, 2, 2]
      norm_cfg: 
        type: naiveSyncBN2d
        eps: 0.001
        momentum: 0.01
      out_channels: [64, 128, 256]
