MODEL:
  MM:
    BBOX_NECK:
      type: FPN
      act_cfg: 
        type: ReLU
      # in_channels: [64, 128, 256]
      in_channels: [128, 256, 512]

      norm_cfg: 
        type: naiveSyncBN2d
        eps: 0.001
        momentum: 0.01
      num_outs: 3
      out_channels: 256
      start_level: 0
