_BASE_: ["../single_timeframe.yml", "../models/centerpoint.yml"]

TAG: "lss"
EVA_DIR: "output_dir/lss"
# EVALUATION: False

GPUS: [0, 1, 2]
EPOCHS: 40
BATCHSIZE: 6
N_WORKERS: 8
VALID_FREQ: 1.0 
GRAD_NORM_CLIP: 10
CKPT_PATH: null

SEMANTIC_SEG:
  NUSCENE_CLASS: True

DATASET:
  DATAROOT: "/home/master/10/cytseng/data/sets/nuscenes/"
  FILTER_INVISIBLE_VEHICLES: True
  VERSION: "v1.0-trainval"
  TRAINING_SAMPLES: -1
  VALIDATING_SAMPLES: 2000

LIFT:
  X_BOUND: [-50.0, 50.0, 0.5] #  Forwards
  Y_BOUND: [-50.0, 50.0, 0.5] # Sides
  Z_BOUND: [-10.0, 10.0, 20.0] # Height

IMAGE:
  N_CAMERA: 6

LOSS:
  SEG_USE: True

OBJ:
  HEAD_NAME: "mm"
