_BASE_: '../single_timeframe.yml'

TAG: 'lss'
EVA_DIR: 'output_dir/lss_mini'

GPUS: [1]
EPOCHS: 50
BATCHSIZE: 6
N_WORKERS: 8
EVALUATION: False
VALID_FREQ: 1.0 
GRAD_NORM_CLIP: 10

DATASET:
  DATAROOT: '/home/master/10/cytseng/data/sets/nuscenes/'
  FILTER_INVISIBLE_VEHICLES: False
  VERSION: 'v1.0-mini'
  TRAINING_SAMPLES: -1

LIFT:
  X_BOUND: [-50.0, 50.0, 0.5]  #  Forwards
  Y_BOUND: [-50.0, 50.0, 0.5]  # Sides
  Z_BOUND: [-10.0, 10.0, 20.0]  # Height

IMAGE:
  N_CAMERA: 6

LOSS:
  SEG_USE: False

OBJ:
  HEAD_NAME: 'mm'
