_BASE_: '../single_timeframe.yml'

TAG: 'lss_oft_multi_cam_mini'
EVA_DIR: 'output_dir/lss_oft_multi_cam_mini'

GPUS: [0, 3]
EPOCHS: 40
BATCHSIZE: 4
N_WORKERS: 6
EVALUATION: False

DATASET:
  FILTER_INVISIBLE_VEHICLES: False
  VERSION: 'v1.0-mini'

IMAGE:
  N_CAMERA: 6

LOSS:
  SEG_USE: True
