_BASE_: '../single_timeframe.yml'

TAG: 'lss_oft'
EVA_DIR: 'output_dir/lss_oft_mini'

GPUS: [0]
EPOCHS: 4
BATCHSIZE: 6
N_WORKERS: 8
EVALUATION: False
VALID_FREQ: 1.0 
GRAD_NORM_CLIP: 10

DATASET:
  FILTER_INVISIBLE_VEHICLES: False
  VERSION: 'v1.0-mini'

IMAGE:
  N_CAMERA: 6

LOSS:
  SEG_USE: False

