_BASE_: '../single_timeframe.yml'

TAG: 'lss_oft'
EVA_DIR: 'output_dir/lss_oft'

GPUS: [0]
EPOCHS: 50
BATCHSIZE: 12
N_WORKERS: 8
EVALUATION: False
VALID_FREQ: 1.0 
GRAD_NORM_CLIP: 10

DATASET:
  DATAROOT: '/home/master/10/cytseng/data/sets/nuscenes/'
  FILTER_INVISIBLE_VEHICLES: False
  VERSION: 'v1.0-trainval'
  TRAINING_SAMPLES: 7000

IMAGE:
  N_CAMERA: 1

LOSS:
  SEG_USE: False
