_BASE_: '../single_timeframe.yml'

TAG: 'lss_oft_single_cam'
EVA_DIR: 'output_dir/lss_oft_single_cam'

GPUS: [1]
EPOCHS: 40
BATCHSIZE: 12
N_WORKERS: 6
EVALUATION: False

DATASET:
  FILTER_INVISIBLE_VEHICLES: False
  VERSION: 'v1.0-trainval'

IMAGE:
  N_CAMERA: 1

LOSS:
  SEG_USE: False
