_BASE_: '../single_timeframe.yml'

TAG: 'lss_oft'
EVA_DIR: 'output_dir/lss_oft'

GPUS: [0]
EPOCHS: 40
BATCHSIZE: 10
N_WORKERS: 4
EVALUATION: False

DATASET:
  FILTER_INVISIBLE_VEHICLES: False
  VERSION: 'v1.0-trainval'

IMAGE:
  N_CAMERA: 6

LOSS:
  SEG_USE: True
