LOG_DIR: '../experiments/nuscenes/baseline'
TAG: 'fiery_4gpus'

GPUS: [0, 1, 2, 3]

BATCHSIZE: 3
PRECISION: 16

TIME_RECEPTIVE_FIELD: 3
N_FUTURE_FRAMES: 4

PRETRAINED:
  LOAD_WEIGHTS: True
  PATH: '/home/wayve/experiments/nuscenes/single_timeframe/10August2021at11:00:51UTC_vm-prod-training-dgx-05_single_timeframe_model/default/version_0/checkpoints/epoch=8-step=14556.ckpt'

PROBABILISTIC:
  ENABLED: True

MODEL:
  BN_MOMENTUM: 0.05
  TEMPORAL_MODEL:
    NAME: 'temporal_block'
    INPUT_EGOPOSE: True

INSTANCE_FLOW:
  ENABLED: True

OPTIMIZER:
  LR: 3e-4

N_WORKERS: 20
