TAG: 'baseline_prob_weight_1.0'

GPUS: [0, 1, 2, 3]

BATCHSIZE: 3
PRECISION: 16

TIME_RECEPTIVE_FIELD: 3
N_FUTURE_FRAMES: 4

PROBABILISTIC:
  ENABLED: True
  WEIGHT: 1.0

PRETRAINED:
  LOAD_WEIGHTS: True
  PATH: '/home/wayve/anthony/fiery/pretrained_weights/static_lift_splat_setting.ckpt'

MODEL:
  BN_MOMENTUM: 0.05
  TEMPORAL_MODEL:
    NAME: 'temporal_block'
    INPUT_EGOPOSE: True

INSTANCE_FLOW:
  ENABLED: True

OPTIMIZER:
  LR: 3e-4

N_WORKERS: 10
